"""In-memory item bank used for the adaptive test MVP."""
from __future__ import annotations

from typing import List

from .cat_engine import Item


ITEMS: List[Item] = [
    Item(
        id="vocab_1",
        domain="vocabulary",
        stem="Choose the correct synonym for 'begin'.",
        options=["finish", "commence", "halt", "cease"],
        correct_key=1,
        model="3pl",
        irt_a=1.2,
        irt_b=-0.5,
        irt_c=0.2,
    ),
    Item(
        id="vocab_2",
        domain="vocabulary",
        stem="Select the best word to complete the sentence: 'She felt a great sense of ____ when she saw the ocean.'",
        options=["awe", "anger", "haste", "loss"],
        correct_key=0,
        model="3pl",
        irt_a=1.1,
        irt_b=0.3,
        irt_c=0.2,
    ),
    Item(
        id="grammar_1",
        domain="grammar",
        stem="Choose the correct form: 'If he ____ earlier, he wouldn't have missed the train.'",
        options=["left", "had left", "leaves", "was leaving"],
        correct_key=1,
        model="2pl",
        irt_a=1.3,
        irt_b=0.1,
    ),
    Item(
        id="grammar_2",
        domain="grammar",
        stem="Identify the grammatically correct sentence.",
        options=[
            "She suggested to go to the museum.",
            "She suggested that we go to the museum.",
            "She suggested us to go to the museum.",
            "She suggested we to go to the museum.",
        ],
        correct_key=1,
        model="2pl",
        irt_a=1.1,
        irt_b=0.6,
    ),
    Item(
        id="listening_1",
        domain="listening",
        stem="Listen to the audio and choose the correct answer.",
        options=[
            "The speaker is talking about weather.",
            "The speaker is giving travel advice.",
            "The speaker is explaining a recipe.",
            "The speaker is discussing financial news.",
        ],
        correct_key=1,
        model="3pl",
        irt_a=1.0,
        irt_b=0.2,
        irt_c=0.2,
        max_plays=2,
        metadata={"audio_url": "https://example.com/audio/travel_tips.mp3"},
    ),
    Item(
        id="listening_2",
        domain="listening",
        stem="Listen to the interview and select the main topic.",
        options=["Education", "Healthcare", "Technology", "Environment"],
        correct_key=2,
        model="3pl",
        irt_a=1.2,
        irt_b=0.8,
        irt_c=0.2,
        max_plays=2,
        metadata={"audio_url": "https://example.com/audio/tech_innovation.mp3"},
    ),
    Item(
        id="english_use_1",
        domain="english_in_use",
        stem="Complete the dialogue with the most natural expression (two correct choices).",
        options=["Not really", "I couldn't agree more", "Absolutely", "I'm afraid so"],
        correct_key=(1, 2),
        model="gpcm",
        irt_a=1.0,
        irt_b=-0.2,
        step_difficulties=[-0.5, 0.3],
    ),
    Item(
        id="english_use_2",
        domain="english_in_use",
        stem="Select appropriate phrasal verbs to fill the blanks (three blanks).",
        options=["turn down", "bring up", "look after", "run into"],
        correct_key=(0, 1, 3),
        model="gpcm",
        irt_a=1.1,
        irt_b=0.4,
        step_difficulties=[0.1, 0.5, 0.9],
    ),
]
